name: Compile the kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_DEFAULT_PLATFORM: linux/arm64   # 新增
    steps:
      - name: Compile the kernel
        uses: trancedj20240410/amlogic-s9xxx-armbian@main
        with:
          build_target: kernel
          kernel_version: 6.6.y
          kernel_auto: true
          kernel_patch: compile-kernel/tools/patch/linux-6.6.y
          auto_patch: true
